package ru.itmo.lab5.command.impl;

import java.util.Optional;
import ru.itmo.lab5.command.AbstractCommand;
import ru.itmo.lab5.exception.CommandException;
import ru.itmo.lab5.exception.InputCancelledException;
import ru.itmo.lab5.io.Console;
import ru.itmo.lab5.io.DragonAsker;
import ru.itmo.lab5.manager.CollectionManager;
import ru.itmo.lab5.model.Dragon;

/**
 * Updates a dragon by id while preserving autogenerated fields.
 */
public class UpdateCommand extends AbstractCommand {
    private final CollectionManager collectionManager;
    private final DragonAsker dragonAsker;
    private final Console console;

    /**
     * Creates the update command.
     *
     * @param collectionManager collection receiver
     * @param dragonAsker builder for complex object input
     * @param console output helper
     */
    public UpdateCommand(CollectionManager collectionManager, DragonAsker dragonAsker, Console console) {
        super("update", "update id {element} : обновить элемент коллекции по id");
        this.collectionManager = collectionManager;
        this.dragonAsker = dragonAsker;
        this.console = console;
    }

    @Override
    public void execute(String arguments) throws CommandException {
        int id = parseId(arguments);
        Optional<Dragon> existing = collectionManager.findById(id);
        if (existing.isEmpty()) {
            throw new CommandException("Элемент с id=" + id + " не найден.");
        }
        try {
            Dragon updated = dragonAsker.askDragon(existing.get().getId(), existing.get().getCreationDate());
            collectionManager.updateById(id, updated);
            console.println("Элемент с id=" + id + " обновлён.");
        } catch (InputCancelledException e) {
            throw new CommandException(e.getMessage(), e);
        }
    }

    private int parseId(String arguments) throws CommandException {
        if (arguments == null || arguments.trim().isEmpty()) {
            throw new CommandException("Нужно указать id. Формат: update id");
        }
        try {
            return Integer.parseInt(arguments.trim());
        } catch (NumberFormatException e) {
            throw new CommandException("id должен быть целым числом.");
        }
    }
}
