package ru.itmo.lab5.io;

import java.util.Arrays;
import java.util.Date;
import java.util.Objects;
import java.util.function.Function;
import java.util.stream.Collectors;
import ru.itmo.lab5.exception.InputCancelledException;
import ru.itmo.lab5.exception.ValidationException;
import ru.itmo.lab5.model.Color;
import ru.itmo.lab5.model.Coordinates;
import ru.itmo.lab5.model.Dragon;
import ru.itmo.lab5.model.DragonCharacter;
import ru.itmo.lab5.model.DragonHead;
import ru.itmo.lab5.model.DragonType;

/**
 * Builds complex domain objects step by step by asking the user for every field separately.
 */
public class DragonAsker {
    private final InputManager inputManager;
    private final Console console;

    /**
     * Creates a new object builder for dragons.
     *
     * @param inputManager current input manager
     * @param console output helper
     */
    public DragonAsker(InputManager inputManager, Console console) {
        this.inputManager = inputManager;
        this.console = console;
    }

    /**
     * Reads all user-defined dragon fields and creates a ready domain object.
     *
     * @param id autogenerated id
     * @param creationDate autogenerated creation date
     * @return ready dragon
     * @throws InputCancelledException if the current input source ends unexpectedly
     */
    public Dragon askDragon(int id, Date creationDate) throws InputCancelledException {
        try {
            String name = askNonEmptyString("Введите name: ");
            Coordinates coordinates = askCoordinates();
            long age = askLongGreaterThanZero("Введите age (> 0) (type long): ");
            Color color = askNullableEnum("Введите color", Color.class);
            DragonType type = askNullableEnum("Введите type", DragonType.class);
            DragonCharacter character = askNullableEnum("Введите character", DragonCharacter.class);
            DragonHead head = askHead();

            return new Dragon(id, name, coordinates, creationDate, age, color, type, character, head);
        } catch (ValidationException e) {
            throw new InputCancelledException("Не удалось создать объект Dragon: " + e.getMessage());
        }
    }

    private Coordinates askCoordinates() throws InputCancelledException {
        try {
            double x = askDouble("Введите coordinates.x (type double): ");
            Float y = askFloatGreaterThan("Введите coordinates.y (> -524) (type Float): ", -524f);
            return new Coordinates(x, y);
        } catch (ValidationException e) {
            throw new InputCancelledException("Не удалось создать coordinates: " + e.getMessage());
        }
    }

    private DragonHead askHead() throws InputCancelledException {
        while (true) {
            String raw = readLine("Введите head.size (type Float) (пустая строка = null для всего head): ");
            if (raw == null) {
                throw new InputCancelledException("Ввод head был прерван.");
            }
            String trimmed = raw.trim();
            if (trimmed.isEmpty()) {
                return null;
            }
            try {
                Float size = Float.valueOf(trimmed);
                int toothCount = askInteger("Введите head.toothCount (type int): ");
                return new DragonHead(size, toothCount);
            } catch (NumberFormatException e) {
                handleInvalidField("Поле head.size должно быть числом float.");
            } catch (ValidationException e) {
                handleInvalidField(e.getMessage());
            }
        }
    }

    private String askNonEmptyString(String prompt) throws InputCancelledException {
        while (true) {
            String raw = readLine(prompt);
            if (raw == null) {
                throw new InputCancelledException("Ввод был прерван.");
            }
            String trimmed = raw.trim();
            if (trimmed.isEmpty()) {
                handleInvalidField("Строка не может быть пустой.");
                continue;
            }
            return trimmed;
        }
    }

    private long askLongGreaterThanZero(String prompt) throws InputCancelledException {
        while (true) {
            String raw = readLine(prompt);
            if (raw == null) {
                throw new InputCancelledException("Ввод был прерван.");
            }
            try {
                long value = Long.parseLong(raw.trim());
                if (value <= 0) {
                    handleInvalidField("Число должно быть больше 0.");
                    continue;
                }
                return value;
            } catch (NumberFormatException e) {
                handleInvalidField("Нужно ввести целое число long.");
            }
        }
    }

    private int askInteger(String prompt) throws InputCancelledException {
        return askUsingParser(prompt, text -> {
            try {
                return Integer.parseInt(text.trim());
            } catch (NumberFormatException e) {
                throw new IllegalArgumentException("Нужно ввести целое число.");
            }
        });
    }

    private double askDouble(String prompt) throws InputCancelledException {
        return askUsingParser(prompt, text -> {
            try {
                return Double.parseDouble(text.trim());
            } catch (NumberFormatException e) {
                throw new IllegalArgumentException("Нужно ввести число double.");
            }
        });
    }

    private Float askFloatGreaterThan(String prompt, float minExclusive) throws InputCancelledException {
        while (true) {
            String raw = readLine(prompt);
            if (raw == null) {
                throw new InputCancelledException("Ввод был прерван.");
            }
            try {
                Float value = Float.valueOf(raw.trim());
                if (value <= minExclusive) {
                    handleInvalidField("Число должно быть больше " + minExclusive + ".");
                    continue;
                }
                return value;
            } catch (NumberFormatException e) {
                handleInvalidField("Нужно ввести число float.");
            }
        }
    }

    private <E extends Enum<E>> E askNullableEnum(String title, Class<E> enumClass) throws InputCancelledException {
        String allowed = Arrays.stream(enumClass.getEnumConstants())
                .map(Enum::name)
                .collect(Collectors.joining(", "));
        E[] values = enumClass.getEnumConstants();
        while (true) {
            String raw = readLine(title + " [" + allowed + "] (пустая строка = null): ");
            if (raw == null) {
                throw new InputCancelledException("Ввод был прерван.");
            }
            String trimmed = raw.trim();
            if (trimmed.isEmpty()) {
                return null;
            }
            try {
                int index = Integer.parseInt(trimmed);
                if (index < 1 || index > values.length){
                    handleInvalidField("Номер от 1 до " + values.length);
                }
                return values[index - 1];
                
            } catch (Exception eo) {
                try {
                    return Enum.valueOf(enumClass, trimmed.toUpperCase());
                } 
                catch (IllegalArgumentException e) {
                handleInvalidField("Недопустимое значение. Разрешено: " + allowed + ".");
                }
            }
        }
    }

    private <T> T askUsingParser(String prompt, Function<String, T> parser) throws InputCancelledException {
        Objects.requireNonNull(parser);
        while (true) {
            String raw = readLine(prompt);
            if (raw == null) {
                throw new InputCancelledException("Ввод был прерван.");
            }
            try {
                return parser.apply(raw);
            } catch (IllegalArgumentException e) {
                handleInvalidField(e.getMessage());
            }
        }
    }

    private String readLine(String prompt) {
        return inputManager.readFieldLine(prompt);
    }

    private void handleInvalidField(String message) throws InputCancelledException {
        if (inputManager.isInteractiveMode()) {
            console.error("Ошибка: " + message);
            console.println("Повторите ввод поля.");
            return;
        }
        throw new InputCancelledException(
                "Ошибка в скрипте (" + inputManager.getCurrentSourceName() + "): " + message
        );
    }
}
