package ru.itmo.lab5.model;

import java.text.SimpleDateFormat;
import java.util.Comparator;
import java.util.Date;
import java.util.Objects;
import ru.itmo.lab5.exception.ValidationException;

/**
 * Main domain class stored inside the collection.
 *
 * <p>The natural order is used by {@link java.util.PriorityQueue}. Dragons are compared
 * primarily by age, then by name, coordinates, head, optional enum fields and finally by id.
 * This gives a stable and predictable order for the queue head and for {@code add_if_min}.</p>
 */
public class Dragon implements Comparable<Dragon> {
    
    private static final Comparator<Dragon> NATURAL_COMPARATOR = Comparator
            .comparingLong(Dragon::getAge)
            .thenComparing(Dragon::getName, String.CASE_INSENSITIVE_ORDER)
            .thenComparingDouble(dragon -> dragon.getCoordinates().getX())
            .thenComparing(dragon -> dragon.getCoordinates().getY())
            .thenComparing(Dragon::getHead, Comparator.nullsLast(Comparator.naturalOrder()))
            .thenComparing(Dragon::getColor, Comparator.nullsLast(Comparator.naturalOrder()))
            .thenComparing(Dragon::getType, Comparator.nullsLast(Comparator.naturalOrder()))
            .thenComparing(Dragon::getCharacter, Comparator.nullsLast(Comparator.naturalOrder()))
            .thenComparing(Dragon::getId);

    private final Integer id;
    private final String name;
    private final Coordinates coordinates;
    private final Date creationDate;
    private final long age;
    private final Color color;
    private final DragonType type;
    private final DragonCharacter character;
    private final DragonHead head;

    /**
     * Creates a validated dragon.
     *
     * @param id autogenerated unique id, must be positive and not null
     * @param name name, must be non-empty and not null
     * @param coordinates coordinates, must not be null
     * @param creationDate creation date, must not be null
     * @param age dragon age, must be greater than 0
     * @param color optional color
     * @param type optional type
     * @param character optional character
     * @param head optional head description
     * @throws ValidationException if any field violates constraints
     */
    public Dragon(
            Integer id,
            String name,
            Coordinates coordinates,
            Date creationDate,
            long age,
            Color color,
            DragonType type,
            DragonCharacter character,
            DragonHead head
    ) throws ValidationException {
        if (id == null) {
            throw new ValidationException("Поле id не может быть null.");
        }
        if (id <= 0) {
            throw new ValidationException("Поле id должно быть больше 0.");
        }
        if (name == null) {
            throw new ValidationException("Поле name не может быть null.");
        }
        if (name.isBlank()) {
            throw new ValidationException("Поле name не может быть пустым.");
        }
        if (coordinates == null) {
            throw new ValidationException("Поле coordinates не может быть null.");
        }
        if (creationDate == null) {
            throw new ValidationException("Поле creationDate не может быть null.");
        }
        if (age <= 0) {
            throw new ValidationException("Поле age должно быть больше 0.");
        }
        this.id = id;
        this.name = name;
        this.coordinates = coordinates;
        this.creationDate = new Date(creationDate.getTime());
        this.age = age;
        this.color = color;
        this.type = type;
        this.character = character;
        this.head = head;
    }

    /**
     * Returns id.
     *
     * @return id
     */
    public Integer getId() {
        return id;
    }

    /**
     * Returns name.
     *
     * @return name
     */
    public String getName() {
        return name;
    }

    /**
     * Returns coordinates.
     *
     * @return coordinates
     */
    public Coordinates getCoordinates() {
        return coordinates;
    }

    /**
     * Returns creation date.
     *
     * @return creation date copy
     */
    public Date getCreationDate() {
        return new Date(creationDate.getTime());
    }

    /**
     * Returns dragon age.
     *
     * @return age
     */
    public long getAge() {
        return age;
    }

    /**
     * Returns color.
     *
     * @return color or null
     */
    public Color getColor() {
        return color;
    }

    /**
     * Returns dragon type.
     *
     * @return type or null
     */
    public DragonType getType() {
        return type;
    }

    /**
     * Returns character.
     *
     * @return character or null
     */
    public DragonCharacter getCharacter() {
        return character;
    }

    /**
     * Returns head description.
     *
     * @return head or null
     */
    public DragonHead getHead() {
        return head;
    }

    @Override
    public int compareTo(Dragon other) {
        return NATURAL_COMPARATOR.compare(this, other);
    }

    @Override
    public String toString() {
        String formattedDate = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(creationDate);
        return "Dragon{"
                + "id=" + id
                + ", name='" + name + '\''
                + ", coordinates=" + coordinates
                + ", creationDate=" + formattedDate
                + ", age=" + age
                + ", color=" + color
                + ", type=" + type
                + ", character=" + character
                + ", head=" + head
                + '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Dragon dragon)) {
            return false;
        }
        return age == dragon.age
                && Objects.equals(id, dragon.id)
                && Objects.equals(name, dragon.name)
                && Objects.equals(coordinates, dragon.coordinates)
                && Objects.equals(creationDate, dragon.creationDate)
                && color == dragon.color
                && type == dragon.type
                && character == dragon.character
                && Objects.equals(head, dragon.head);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, coordinates, creationDate, age, color, type, character, head);
    }
}
